# GitHub Pages configuration for the Minimal Mistakes remote theme.
remote_theme: "mmistakes/minimal-mistakes"

locale: "zh-CN"
title: "宗雨辰"
name: "宗雨辰"
description: "个人网站"
url: "https://jongwoocheon.github.io"
baseurl: ""

include:
  - _pages

plugins:
  - jekyll-include-cache
